### ISSUE TITLE
Add pre-req

### ISSUE THREAD

**Issue by ezYakaEagle442** [lgmorand/workshop-aca#19]
- [https://aka.ms/aca-workshop](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Faca-workshop&data=05%7C01%7Csteve.pincaud%40microsoft.com%7Cce6d4dab10f54ba7460708db085858dd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638112947926345789%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wcijKVqKVzSJYSjIDsOCXEx0W89ZOESHiwXfMNcmwDE%3D&reserved=0) stoacawks.z6.web.core.windows.net URL must be allowed from browsers

- Regarding Aure Prod [CLI](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fcli%2Fazure%2Fazure-cli-endpoints%3Ftabs%3Dazure-cloud%23extension-endpoints&data=05%7C01%7Csteve.pincaud%40microsoft.com%7Cce6d4dab10f54ba7460708db085858dd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638112947926345789%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=awQclMDu1gHxafwAugQISDYJnImPUUpPzDs0uLz78tM%3D&reserved=0), endpoint azcliprod.blob.core.windows.net must be allowed too, this is a requirement to install [aca extension](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fcontainer-apps%2Fget-started-existing-container-image%3Ftabs%3Dbash%26pivots%3Dcontainer-apps-public-registry%23prerequisites&data=05%7C01%7Csteve.pincaud%40microsoft.com%7Cce6d4dab10f54ba7460708db085858dd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638112947926345789%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lWwQHdEIhzdnqZdytyOWG%2B6P99PXCkG4IubALhYTMYM%3D&reserved=0) : az extension add --name containerapp –upgrade 

- [Bicep](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fazure-resource-manager%2Fbicep%2Finstall%23azure-cli&data=05%7C01%7Csteve.pincaud%40microsoft.com%7Cce6d4dab10f54ba7460708db085858dd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638112947926345789%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zzQDQZZS84nsPyfV3bxElNez5IW9iiaeU8VYwv78HEo%3D&reserved=0) is also required for Lab 2: URL below must be whitelisted

- [downloads.bicep.azure.com](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdownloads.bicep.azure.com%2F&data=05%7C01%7Csteve.pincaud%40microsoft.com%7Cce6d4dab10f54ba7460708db085858dd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638112947926345789%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=f%2Bu5wBqf874J2aD4aoZtyIUyc6NPiKCcB3WjHgamsoI%3D&reserved=0) & [downloads.bicep.azure.com/releases/latest](https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdownloads.bicep.azure.com%2Freleases%2Flatest&data=05%7C01%7Csteve.pincaud%40microsoft.com%7Cce6d4dab10f54ba7460708db085858dd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638112947926345789%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=uTP69YNQ7rwXIXeHZ9gJxqKH7aWLPd1YML3i3nmKano%3D&reserved=0)

-  [https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fbicep%2Freleases%2Flatest%2Fdownload%2Fbicep-linux-x64&data=05%7C01%7Csteve.pincaud%40microsoft.com%7Cce6d4dab10f54ba7460708db085858dd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638112947926345789%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rqlxV0U1XVwxtWM12VA3N%2FkXTZM3MYKKPGKx%2FsnE3QU%3D&reserved=0)  

- ([https://github.com/Azure/bicep/releases/latest/download/bicep-osx-x64](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fbicep%2Freleases%2Flatest%2Fdownload%2Fbicep-osx-x64&data=05%7C01%7Csteve.pincaud%40microsoft.com%7Cce6d4dab10f54ba7460708db085858dd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638112947926345789%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IabDkiEGNqPPOpHOjiJEz60x26Gr6B%2F7pdrV1CUsrWs%3D&reserved=0) for mac OS)

**Comment by lgmorand** [comment]
c'est un faux problème qui n'est pas lié au workshop en lui-même. si les gens bloquent les URLs d'Azure, ils ne faut pas qu'ils fassent un lab azure
